### ISSUE TITLE
`groupby-2-way` tables are not written to the correct directory

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/safetab-action#20]
Given the following table configuration (the `tables` property)...

```yaml
tables:
  two_way:
    tab_type: 2-way
    variables:
      - sex
      - age_band
  target_two_way:
    tab_type: target-2-way
    target: has_copd
    variables:
      - sex
      - age_band
  groupby_two_way:
    tab_type: groupby-2-way
    groupby: age_band
    variables:
      - sex
      - has_copd
    outputs:
      moderately_sensitive:
        safetab_log: output/input_tables/table_log.txt
        safetab_two_way: output/input_tables/two_way/*.md
        safetab_target_two_way: output/input_tables/target_two_way/*.md
        safetab_groupby_two_way: output/input_tables/groupby_two_way/*.md
```

...the `groupby-2-way` table called `groupby_two_way` is written to the `target_two_way` directory.
